-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 12:43:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema final
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `final` ;

-- -----------------------------------------------------
-- Schema final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final` DEFAULT CHARACTER SET utf8 ;
USE `final` ;

-- -----------------------------------------------------
-- Table `final`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `final`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`producto` ;

CREATE TABLE IF NOT EXISTS `final`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_proveedor_idx` (`proveedor_idproveedor` ASC) ,
  CONSTRAINT `fk_producto_proveedor`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `final`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`cliente` ;

CREATE TABLE IF NOT EXISTS `final`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `telefono_cliente` VARCHAR(45) NOT NULL,
  `direccion_cliente` VARCHAR(45) NOT NULL,
  `DNI` INT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`factura` ;

CREATE TABLE IF NOT EXISTS `final`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `IVA` FLOAT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_factura_cliente1_idx` (`cliente_idcliente` ASC) ,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `final`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final`.`detalle_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final`.`detalle_factura` ;

CREATE TABLE IF NOT EXISTS `final`.`detalle_factura` (
  `iddetalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `importe` DOUBLE NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `factura_idfactura` INT NOT NULL,
  PRIMARY KEY (`iddetalle`),
  INDEX `fk_ventas_producto1_idx` (`producto_idproducto` ASC) ,
  INDEX `fk_detalle_factura_factura1_idx` (`factura_idfactura` ASC) ,
  CONSTRAINT `fk_detalle_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `final`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_factura_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `final`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
